export enum ROLE {
    CREATE_USER = "create_user",
    UPDATE_USER = "update_user",
    VIEW_USERS = "view_users",
    VIEW_USER_BY_ID = "view_single_user",
    DELETE_USER = "delete_user"
}


//role: 1
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb3VuZCI6eyJpZCI6ImJhMDdjNWJjLTVlYjItNGQ2ZC1iYjA0LTRlZTI1Y2JhYzJjNCIsIm5hbWUiOiJzdXJlc2giLCJlbWFpbCI6InN1cmVzaEBnbWFpbC5jb20iLCJwYXNzd29yZCI6InN1cmVzaEAxMjMiLCJtb2JpbGVfbm8iOiI5MDM4Mzg5MjkxIiwiY3JlYXRlZF9hdCI6IjIwMjMtMDctMTlUMDU6NDA6NDUuMzU1WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA3LTE5VDA1OjQwOjQ1LjM1NVoifSwiaWF0IjoxNjg5NzY1MTIwLCJleHAiOjE2OTQ5NDkxMjB9.xaHer7tEa6inUuBZV3RHeIhow6wT4SJVXmXzX0EpRbk

